AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS WAF Rules for FineAcers'

Resources:
  FineAcersWebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: FineAcersWebACL
      Scope: REGIONAL
      DefaultAction:
        Allow: {}
      Rules:
        - Name: RateLimitRule
          Priority: 1
          Statement:
            RateBasedStatement:
              Limit: 2000
              AggregateKeyType: IP
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: RateLimitRule

        - Name: SQLiRule
          Priority: 2
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesSQLiRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: SQLiRule

        - Name: XSSRule
          Priority: 3
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: XSSRule

        - Name: GeoBlockRule
          Priority: 4
          Statement:
            NotStatement:
              Statement:
                GeoMatchStatement:
                  CountryCodes:
                    - IN
                    - US
                    - AE
                    - GB
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: GeoBlockRule

        - Name: IPWhitelistRule
          Priority: 5
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt WhitelistIPSet.Arn
          Action:
            Allow: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: IPWhitelistRule

  WhitelistIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: FineAcersWhitelist
      Scope: REGIONAL
      IPAddressVersion: IPV4
      Addresses:
        - 192.168.1.0/24
        - 10.0.0.0/8