openapi: 3.0.0
info:
  title: FineAcers API
  version: 1.0.0
  description: Marketing Automation API
paths:
  /api/leads:
    post:
      summary: Create a new lead
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lead'