version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: fineacers-n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_password
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-workflows:/workflows
    depends_on:
      - postgres
    networks:
      - fineacers-network

  postgres:
    image: postgres:14
    container_name: fineacers-postgres
    restart: always
    environment:
      - POSTGRES_USER=fineacers
      - POSTGRES_PASSWORD=secure_password
      - POSTGRES_DB=fineacers_automation
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - fineacers-network

  redis:
    image: redis:7-alpine
    container_name: fineacers-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fineacers-network

volumes:
  n8n_data:
  postgres_data:
  redis_data:

networks:
  fineacers-network:
    driver: bridge