version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: fineacers-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - fineacers-network

  grafana:
    image: grafana/grafana
    container_name: fineacers-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3001:3000"
    networks:
      - fineacers-network

  node-exporter:
    image: prom/node-exporter
    container_name: fineacers-node-exporter
    ports:
      - "9100:9100"
    networks:
      - fineacers-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  fineacers-network:
    external: true